name: BigRob
favicon: null
layout_spectrum: 0.56613
typography_spectrum: 0.11609
title: Embrace the Rapture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7996ee'
    - '#16181f'
    - '#fefefe'
    - '#5a5c5b'
    - '#bdbbad'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
