name: BigRob
favicon: null
layout_spectrum: 0.5526392413303256
typography_spectrum: 0.31611024867743254
title: Embrace the Rapture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.26901723840273917
  lightness: 0.7526679069269449
  saturation: 0.3403488777112216
  rhythmicContrast: 0.3758863646071404
purpose: []
