name: BigRob
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15462
title: Embrace the Rapture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3d3f3c'
    - '#bebce4'
    - '#ee0705'
    - '#8c9489'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
